
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: teste-6
  name: teste-6
spec:
  replicas: 3
  selector:
    matchLabels:
      app: teste-6
  template:
    metadata:
      labels:
        app: teste-6
    spec:
      containers:
      - image: bbeckerdarosa/teste-6:latest
        name: teste-6
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        env:
        - name: MEU_TESTE
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: user
status: {}