apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hello-barbara
  name: hello-barbara
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: hello-barbara
  template:
    metadata:
      labels:
        run: hello-barbara
    spec:
      containers:
      - image: bbeckerdarosa/hello-barbara-1:latest
        imagePullPolicy: Always
        name: hello-barbara-1
        resources: {}
        ports:
          - containerPort: 80
      restartPolicy: Always