
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-barbara
  name: hello-barbara
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-barbara
  template:
    metadata:
      labels:
        app: hello-barbara
    spec:
      containers:
      - image: bbeckerdarosa/hello-barbara-4:latest
        name: hello-barbara-1
        imagePullPolicy: Always
        env:
          - name: TESTE
            value: Utilizando variavel de ambiente
        ports:
          - containerPort: 5000
status: {}