apiVersion: v1
kind: Service
metadata:
  name: hello-barbara
  labels:
    run: hello-barbara
  namespace: default
spec:
  ports:
  - nodePort: 32145
    port: 80
    targetPort: 80   
  selector:
    run: hello-barbara
  type: NodePort 