apiVersion: v1
kind: Service
metadata:
  labels:
    run: teste-6
  name: teste-6
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: teste-6
  type: ClusterIP