apiVersion: v1
kind: Service
metadata:
  name: hello-barbara
  labels:
    run: hello-barbara
spec:
  type: NodePort
  selector:
    app: hello-barbara
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010