apiVersion: v1
kind: Service
metadata:
  name: hello-barbara
  labels:
    run: hello-barbara
  namespace: default
spec:
  ports:
  - nodePort: 32145
    port: 5000
    targetPort: 5000   
  selector:
    app: hello-barbara
  type: NodePort 